export enum BiomeTypes {
    // OCEAN = "OCEAN",
    PLAINS = "PLAINS",
    DESERT = "DESERT",
    // EXTREME_HILLS = "EXTREME_HILLS",
    // FOREST = "FOREST",
    // TAIGA = "TAIGA",
    // SWAMPLAND = "SWAMPLAND",
    // RIVER = "RIVER",
    // NETHER = "NETHER",
    // SKY = "SKY",
    // FROZEN_OCEAN = "FROZEN_OCEAN",
    // FROZEN_RIVER = "FROZEN_RIVER",
    // ICE_PLAINS = "ICE_PLAINS",
    // ICE_MOUNTAINS = "ICE_MOUNTAINS",
    // MUSHROOM_ISLAND = "MUSHROOM_ISLAND",
    // MUSHROOM_ISLAND_SHORE = "MUSHROOM_ISLAND_SHORE",
    // BEACH = "BEACH",
    // DESERT_HILLS = "DESERT_HILLS",
    // FOREST_HILLS = "FOREST_HILLS",
    // TAIGA_HILLS = "TAIGA_HILLS",
    // EXTREME_HILLS_EDGE = "EXTREME_HILLS_EDGE",
    // JUNGLE = "JUNGLE",
    // JUNGLE_HILLS = "JUNGLE_HILLS",
    // JUNGLE_EDGE = "JUNGLE_EDGE",
    // DEEP_OCEAN = "DEEP_OCEAN",
    // STONE_BEACH = "STONE_BEACH",
    // COLD_BEACH = "COLD_BEACH",
    // BIRCH_FOREST = "BIRCH_FOREST",
    // BIRCH_FOREST_HILLS = "BIRCH_FOREST_HILLS",
    // ROOFED_FOREST = "ROOFED_FOREST",
    // COLD_TAIGA = "COLD_TAIGA",
    // COLD_TAIGA_HILLS = "COLD_TAIGA_HILLS",
    // MEGA_TAIGA = "MEGA_TAIGA",
    // MEGA_TAIGA_HILLS = "MEGA_TAIGA_HILLS",
    // EXTREME_HILLS_PLUS= "EXTREME_HILLS_PLUS",
    // SAVANNA = "SAVANNA",
    // SAVANNA_PLATEAU = "SAVANNA_PLATEAU",
    // MESA = "MESA",
    // MESA_PLATEAU_F = "MESA_PLATEAU_F",
    // MESA_PLATEAU = "MESA_PLATEAU"
}

export enum BlockTypes {
    BEDROCK = "BEDROCK",
    DIAMOND_ORE = "DIAMOND_ORE",
    GOLD_ORE = "GOLD_ORE",
    IRON_ORE = "IRON_ORE",
    COAL_ORE = "COAL_ORE",
    STONE = "STONE",
    DIRT = "DIRT",
    GRASS = "GRASS",
    OAK_TRUNK = "OAK_TRUNK",
    OAK_LEAF = "OAK_LEAF",
    AIR = "AIR",
    WATER = "WATER",
    LAVA = "LAVA"
}

export enum WorldGernerationStages {
    GENERATION_STARTED = "GENERATION_STARTED",
    GENERATION_OF_CHUNKS_STARTED = "GENERATION_OF_CHUNKS_STARTED",
    GENERATION_OF_CHUNKS_FINISHED = "GENERATION_OF_CHUNKS_FINISHED",
    GENERATION_OF_ORE_STARTED = "GENERATION_OF_ORE_STARTED",
    GENERATION_OF_ORE_FINISHED = "GENERATION_OF_ORE_FINISHED",
    GENERATION_OF_CAVE_STARTED = "GENERATION_OF_CAVE_STARTED",
    GENERATION_OF_CAVE_FINISHED = "GENERATION_OF_CAVE_FINISHED",
    GENERATION_OF_BUILDINGS_STARTED = "GENERATION_OF_BUILDINGS_STARTED",
    GENERATION_OF_BUILDINGS_FINISHED = "GENERATION_OF_BUILDINGS_FINISHED",
    GENERATION_FINISHED = "GENERATION_FINISHED",
    "CONTINUATION.GENERATION_STARTED" = "CONTINUATION.GENERATION_STARTED",
    "CONTINUATION.GENERATION_OF_CHUNKS_STARTED" = "CONTINUATION.GENERATION_OF_CHUNKS_STARTED",
    "CONTINUATION.GENERATION_OF_CHUNKS_FINISHED" = "CONTINUATION.GENERATION_OF_CHUNKS_FINISHED",
    "CONTINUATION.GENERATION_OF_ORE_STARTED" = "CONTINUATION.GENERATION_OF_ORE_STARTED",
    "CONTINUATION.GENERATION_OF_ORE_FINISHED" = "CONTINUATION.GENERATION_OF_ORE_FINISHED",
    "CONTINUATION.GENERATION_OF_CAVE_STARTED" = "CONTINUATION.GENERATION_OF_CAVE_STARTED",
    "CONTINUATION.GENERATION_OF_CAVE_FINISHED" = "CONTINUATION.GENERATION_OF_CAVE_FINISHED",
    "CONTINUATION.GENERATION_OF_BUILDINGS_STARTED" = "CONTINUATION.GENERATION_OF_BUILDINGS_STARTED",
    "CONTINUATION.GENERATION_OF_BUILDINGS_FINISHED" = "CONTINUATION.GENERATION_OF_BUILDINGS_FINISHED",
    "CONTINUATION.GENERATION_FINISHED" = "CONTINUATION.GENERATION_FINISHED"
}

export enum MoveDirections {
    MOVE_LEFT = "MOVE_LEFT",
    MOVE_RIGHT = "MOVE_RIGHT",
    MOVE_UP = "MOVE_UP",
    MOVE_DOWN = "MOVE_DOWN"
}

export enum DeathReasons {
    FELL_OF_ONE_PLACE_AUTO = "FELL_FROM_A_HIGH_PLACE",
    FELL_ON_FLOOR_WITH_TOO_FORCE = "FELL_ON_FLOOR_WITH_TOO_FORCE",
    TRIED_SWIMMING_IN_LAVA = "TRIED_SWIMMING_IN_LAVA",
    WAS_BURNED_ALIVE = "WAS_BURNED_ALIVE"
}